// const tintColor = '#2f95dc';
const tintColor = '#FE5665';

export default {
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  // primaryColor: '#FE5665',
  header_color: '#FFf',
  secondColor: '#19245A',
  blue_shade: '#3B5998',
  gray_light: '#DEDFE1',
  dark_gray: '#5A5B5D',
  gray_shade: '#1D1D1D',
  white_color: '#fff',
  gray_shade_new: '#595A5C',
  lighter_gray: '#E6E7E8',
  bg_color: '#f6f6f8',
  radio_button_color: '#00a0e6',
  radio_btn_inactive_color: '#dfdfdf',
  white_bg_color: '#ffffff',
  cross_icon_color: '#eb261d',
  gray_color_opecity: 'rgba(65,63,64,0.7)',
  start_color: '#ff7284',
  end_color: '#FE5665',
  light_text_color: '#909090',
  separator_color: '#e5e5e5',
  text_color: '#696969',
  name_txt: '#393939',
  view_style: '#EDEEF3',
};
