export default {
  workout: 'WORKOUT',
  profile: 'Profile',
  edit_profile: 'View Profile ',
  feed: 'Request an Item',
  my_feed: 'MY Feed',
  FeedComments: 'all Comments',
  create_feed: 'create feed',
  EditFeed: 'edit feed',
  settings: 'Bid',
  notification: 'Notification',
  share_app: 'Share App',
  privacy_policy: 'Hire',
  term_condition: 'Find Business',
  delete_account: 'Delete Account',
  contact_us: 'Catalogues',
  logout: 'Logout',
  login: 'Login',
  about_us: 'Products Map',
  my_workout: 'MY WORKOUT',
  comments: 'Comments',
  faq: 'Specials',
  change_password: 'Categories',
  near_by: 'Buy',
  feed_new: 'Category',

  my_Favirity: 'My Favorites',
  my_Reviews: 'My Reviews',
  rate_the_app: 'Rate The Application',
  give_feedback: 'Give Feedback',
  my_request: 'My Request',
  incoming_request: 'Incoming Requests',
  my_request_stack: 'My Request',

  TRUE: true,
  FALSE: false,
  SUCCESS: true,
  ALREADY: 'already',
  LOGGEDIN: 'loggedIn',
  USERINFO: 'userinfo',
  addToCart: 'addToCart',
  FoodAPI: 'FoodAPI',
  WARNING: false,
  message: 'Something went wrong',
  FACEBOOK: 'facebook',
  user_like: 'true',
  user_unlike: 'false',
};
