export default {
  workout: require('../assets/menu/Hire.png'),
  profile: require('../assets/menu/Hire.png'),
  edit_profile: require('../assets/menu/Hire.png'),
  feed: require('../assets/menu/request.png'),
  my_feed: require('../assets/menu/Hire.png'),
  FeedComments: require('../assets/menu/Hire.png'),
  create_feed: require('../assets/menu/Hire.png'),
  EditFeed: require('../assets/menu/Hire.png'),
  settings: require('../assets/menu/bid.png'),
  notification: require('../assets/menu/Hire.png'),
  share_app: require('../assets/menu/feedback.png'),
  privacy_policy: require('../assets/menu/Hire.png'),
  term_condition: require('../assets/menu/search.png'),
  delete_account: require('../assets/menu/Hire.png'),
  contact_us: require('../assets/menu/catalogue.png'),
  logout: require('../assets/menu/logout.png'),
  about_us: require('../assets/menu/maps.png'),
  my_workout: require('../assets/menu/Hire.png'),
  comments: require('../assets/menu/Hire.png'),
  faq: require('../assets/menu/specials.png'),
  change_password: require('../assets/menu/Hire.png'),
  // filter: 'Sort Order',
  near_by: require('../assets/menu/cart.png'),

  my_Favirity: require('../assets/menu/heart.png'),
  my_Reviews: require('../assets/menu/clip.png'),
  rate_the_app: require('../assets/menu/rating.png'),
  give_feedback: require('../assets/menu/feedback.png'),

  TRUE: true,
  FALSE: false,
  SUCCESS: true,
  ALREADY: 'already',
  LOGGEDIN: 'loggedIn',
  USERINFO: 'userinfo',
  addToCart: 'addToCart',
  FoodAPI: 'FoodAPI',
  WARNING: false,
  message: 'Something went wrong',
  FACEBOOK: 'facebook',
  user_like: 'true',
  user_unlike: 'false',
};
